INSERT INTO RESTAURANT_ROLES (ROLE)
SELECT t.ROLE
    FROM(
        values ('ADMIN')
             ,('KITCHEN')
        ) AS t(ROLE)
    WHERE NOT EXISTS (
    SELECT * FROM RESTAURANT_ROLES
);


INSERT INTO RESTAURANT_USER( PASSWORD, USERNAME, ROLES_ID)
SELECT '$2a$12$yqj68AqYLhEmLGSmWrMmNuWEArEcBD07FY3S/ElOc8kxm7ekwc4pC', 'farid', 1
    WHERE NOT EXISTS (
    SELECT * FROM RESTAURANT_USER
);



